default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: "pre-commit: checking YAML"
        exclude: ^app-deploy/templates
      - id: end-of-file-fixer
        name: "pre-commit: checking end of file"
      - id: trailing-whitespace
        name: "pre-commit: checking trailing whitespace"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: "black: checking code formatting"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [check, --select, I001, ., --fix, --exit-non-zero-on-fix, --extend-ignore, E501]
